sudo: required

services:
  - docker

before_script:
  # rmk: this will pull the image from dockerhub,
  # so dockerhub must be up to date
  - make docker_run

script:
  - make pull_binary
  - docker exec -it tess3_article make article

# see https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Article/draft.pdf
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
